name: Create Release and Crate Asset

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo

      - name: Install Cargo Edit
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install cargo-edit

      - name: Calculate Next Version
        id: versioning
        uses: AABelkhiria/next-version@v1
        with:
          mode: 'git-calver'

      - name: Update version in Cargo.toml
        run: |
            cargo set-version ${{ steps.versioning.outputs.new-version }}
            echo "version=${{ steps.versioning.outputs.new-version }}"
        
      - name: Package the crate
        run: cargo package --allow-dirty

      - name: Create GitHub Release and Upload Crate
        uses: softprops/action-gh-release@v1
        with:
          # The tag is created from the version in Cargo.toml
          tag_name: ${{ steps.versioning.outputs.new-version }}
          # The files to upload as assets
          files: "target/package/*.crate"
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
