name: Create Release and Crate Asset

on:
  pull_request:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    env:
      CRATE_NAME: "decorator"

    outputs:
      new_version: ${{ steps.versioning.outputs.new-version }}

    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo

      - name: Install Cargo Edit
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install cargo-edit

      - name: Calculate Next Version
        id: versioning
        uses: AABelkhiria/next-version@v1
        with:
          mode: 'git-semver'

      - name: Update version in Cargo.toml
        run: |
            cargo set-version ${{ steps.versioning.outputs.new-version }}
            echo "version=${{ steps.versioning.outputs.new-version }}"

      - name: Publish To Ash Registry
        uses: AABelkhiria/ash-registry@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-token: ${{ secrets.REGISTRY_TOKEN }}
