name: Update Crate Registry

on:
  workflow_call:
    inputs:
      new_version:
        description: 'The new crate version tag (e.g., 25.8.1)'
        required: true
        type: string

jobs:
  update_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download crate artifact from the calling workflow
        uses: actions/download-artifact@v4
        with:
          name: crate-package
          path: ./crate_package

      - name: Prepare registry update information
        id: prep
        run: |
          CRATE_VERSION="${{ inputs.new_version }}"
          CRATE_FILE=$(find ./crate_package -name "*.crate")
          CHECKSUM=$(sha256sum $CRATE_FILE | cut -d' ' -f1)
          CRATE_NAME=$(basename $CRATE_FILE | sed "s/-$CRATE_VERSION.crate//")
          
          echo "CRATE_FILE_PATH=$CRATE_FILE" >> $GITHUB_ENV
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV
          echo "CRATE_NAME=$CRATE_NAME" >> $GITHUB_ENV
          echo "CRATE_VERSION=$CRATE_VERSION" >> $GITHUB_ENV

          if [ ${#CRATE_NAME} -le 3 ]; then
            INDEX_PATH_DIR="${#CRATE_NAME}"
          else
            INDEX_PATH_DIR="${CRATE_NAME:0:2}/${CRATE_NAME:2:2}"
          fi
          echo "INDEX_PATH_DIR=$INDEX_PATH_DIR" >> $GITHUB_ENV

      # === Section 1: Update the Registry Index Branch ===
      - name: Checkout registry-index branch
        uses: actions/checkout@v4
        with:
          ref: registry-index
          path: ./registry-index-dir
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update files in registry-index
        env:
          GH_PAGES_URL: "https://aabelkhiria.github.io/decorator-lib-rs"
          API_URL: "https://github.com/${{ github.repository }}"
        run: |
          cd ./registry-index-dir

          # 1. Create config.json, pointing downloads to GitHub Pages
          CONFIG_JSON_PATH="config.json"
          if [ ! -f "$CONFIG_JSON_PATH" ]; then
            echo "Creating config.json..."
            DL_URL="${GH_PAGES_URL}/crates/{crate}-{version}.crate" # Note the filename format
            echo "{\"dl\":\"$DL_URL\",\"api\":\"$API_URL\"}" > $CONFIG_JSON_PATH
          fi

          # 2. Update the sparse index file
          mkdir -p "index/${INDEX_PATH_DIR}"
          INDEX_FILE="index/${INDEX_PATH_DIR}/${CRATE_NAME}"
          DEPS="[]"
          NEW_VERSION_JSON="{\"name\":\"${CRATE_NAME}\",\"vers\":\"${CRATE_VERSION}\",\"deps\":${DEPS},\"cksum\":\"${CHECKSUM}\",\"features\":{},\"yanked\":false}"
          echo $NEW_VERSION_JSON >> $INDEX_FILE

      - name: Commit and Push to registry-index
        run: |
          cd ./registry-index-dir
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update index for ${{ env.CRATE_NAME }} v${{ env.CRATE_VERSION }}"
            git push
          else
            echo "No changes to commit to registry-index."
          fi

      # === Section 2: Update the GitHub Pages Branch ===
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages-dir
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy .crate file to gh-pages checkout
        run: |
          # Create the destination directory
          mkdir -p ./gh-pages-dir/crates
          # Copy the artifact, renaming it to match the download URL format
          cp ${{ env.CRATE_FILE_PATH }} ./gh-pages-dir/crates/${{ env.CRATE_NAME }}-${{ env.CRATE_VERSION }}.crate

      - name: Commit and Push to gh-pages
        run: |
          cd ./gh-pages-dir
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Add artifact for ${{ env.CRATE_NAME }} v${{ env.CRATE_VERSION }}"
            git push
          else
            echo "No changes to commit to gh-pages."
          fi